//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3build
    {
        public string Location { get; set; }
        public string CarPlate { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string Zone { get; set; }
        public Nullable<double> Gate { get; set; }
        public string Carin_out { get; set; }
        public Nullable<double> avg_h { get; set; }
        public Nullable<double> avg_m { get; set; }
        public string F9 { get; set; }
        public Nullable<double> avg_sty { get; set; }
        public double no_id { get; set; }
    }
}
