//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3in1data
    {
        public string Location { get; set; }
        public string CarPlate { get; set; }
        public string Date_Time { get; set; }
        public string zone { get; set; }
        public Nullable<double> gate { get; set; }
        public string in_out { get; set; }
        public string avg_h { get; set; }
        public string avg__m { get; set; }
        public Nullable<double> Capacity { get; set; }
        public double No_id { get; set; }
    }
}
