//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace highchart_line.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarPark_SystemEntities9 : DbContext
    {
        public CarPark_SystemEntities9()
            : base("name=CarPark_SystemEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C3build> C3build { get; set; }
        public virtual DbSet<C3in1data> C3in1data { get; set; }
        public virtual DbSet<inout_time_off> inout_time_off { get; set; }
    }
}
